### ISSUE TITLE
Create "Save" and "Save and Exit" Buttons for Editing

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#116]
UAT revealed that some users would like to be able to Save an item they are editing before leaving the editing page. This reassures them that the data they have entered has not changed upon leaving the page, and that they submitted correctly. 

Editing pages should implement a "Save" button, that saves the item to the database without leaving the page, and a "Save and Exit" button that behaves as the current button does.

**Comment by Daniel-Jang** [comment]
Pull Request: https://github.com/cass-degrees/CASS-Degrees-Code/pull/178
