### ISSUE TITLE
Redesign Requisite and Incompatible Fields on Course Pages

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#124]
UAT found that the multiselect fields for adding/removing course Requisites and Incompatibilities was extremely confusing. Users assumed that the options in the field were Requisites that had already been added without their choice, and they tried to delete them with backspace. 

A search and add table would be an effective solution. A search bar filters courses, and selecting them adds the course to a table. Selected courses can then be removed from the table after. 

Related to issue #78.

**Comment by JackSekoranja** [comment]
Closed with PR #156
