### ISSUE TITLE
Put Year-Specific Units (5)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#13]
As a CASS Staff member, 
I want to be able to insert a specified number of year-specific (1000, 2000, 3000, etc.) units to a degree template,
So that It properly reflects to students the units required by the program.

**Acceptance Criteria:**
- While editing a program template, the user has the option of adding a number of year-specific courses by inputting a number of units (that is divisible by 6) and then the target year for the courses (1000, 2000, 3000)
- Once this field has been added, the template has changed to indicate the presence of these courses, clearly indicating the number of units and the year of the courses

**Comment by spencerj411** [comment]
closed - see #112
