### ISSUE TITLE
Put Subject-Specific Units (5)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#14]
As a CASS Staff member, 
I want to be able to insert a specified number of subject-specific electives (e.g. ARTS) when creating degree templates,
So that It properly reflects to students the units required by the program.

**Acceptance Criteria:**
- While editing a program template, the user has the option of adding a number of subject-specific courses by inputting a number of units (that is divisible by 6) and then the four-letter subject code
- Once this field has been added, the template has changed to indicate the presence of these courses, clearly indicating the number of units and the subject code

**Comment by spencerj411** [comment]
closed - see #111
