### ISSUE TITLE
Bug - Deleting A Subplan

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#141]
When checking if a program uses a certain subplan before deleting it, it seems like the code assumes that every program has a subplan. I am able to reproduce the bug by selecting to delete a subplan that is not part of any program (throws a `KeyError` with exception value `ids`). When I select a subplan that is part of a program (when program rules has the `ids `field), it works.

**Comment by KavsHub** [comment]
@spencerj411 are you sure? I can't seem to reproduce the bug. I made a subplan (fresh so not linked to anything) then I deleted it with no problems.

I'll double check the code and make it ignore checking if no programs use the subplan currently being deleted.

**Comment by KavsHub** [comment]
Found the bug and fixed in PR #145
