### ISSUE TITLE
PDF and View on server resulting in error

### ISSUE THREAD

**Issue by joshcbee** [j-selby/CASS-Degrees-Code#167]
![image](https://user-images.githubusercontent.com/10462891/58535725-f4962600-8231-11e9-89aa-612ed45371e9.png)

![image](https://user-images.githubusercontent.com/10462891/58535754-feb82480-8231-11e9-91c1-f16a75830e04.png)

**Comment by j-selby** [comment]
@JackSekoranja can this be closed then?

**Comment by JackSekoranja** [comment]
While invalid data will still cause this issue, it is no longer possible to input invalid data in to the system from the staff user interface (PR #168).
