### ISSUE TITLE
Add Timestamp for Plan (2)

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#187]
As a _Student_,
I want my plan to contain a timestamp that displays the time and date it was last updated,
So that I can tell how recent the plan is.

**Acceptance Criteria:**

- Plan displays the time and date it was last updated
- Plan updates its timestamp when it is edited.
- Plan does not update its timestamp when it is loaded but no changes are made.

**User Story Points:** 2

**Comment by JackSekoranja** [comment]
Closed with PR #232
