### ISSUE TITLE
Add Subplan to Program Plan (8)

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#199]
As a _Student_,
I want to be able to add subplans to my program plan,
So that I can indicate my intended/actual completion of that subplan

**Acceptance Criteria:**

- There exists a way in which to indicate what subplans are/will be completed by the program plan
- Adding a subplan to the program correctly adds the requirements of that subplan to the program plan

**User Story Points:** 8

**Comment by JackSekoranja** [comment]
Closed with PR #298
