### ISSUE TITLE
Openable/Editable Plan via Email (8)

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#208]
As a _Student/CASS Staff Member_,
I want to be able to send my plan in an email,
So that I can get CASS Staff/Students to view my changes in the plan

**Acceptance Criteria:**

- The plan must be able to be opened and edited by the party receiving the email

**User Story Points:** 8

**Comment by JackSekoranja** [comment]
Closed with PR #242
