### ISSUE TITLE
Make Bulk Upload Compatible with CASS' .xlsx Format

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#217]
**(FEEDBACK FROM CASS' USER TESTING)**

> "_Is it possible to do a mass upload of courses from the 3-year teaching plan (stored, I think, as a spreadsheet)?_" -Deborah Veness

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit
Excel Spreadsheet Format: https://drive.google.com/open?id=1EdQHhrNSd2QhO4c2A_su3x3K7hHQKQoI

**Comment by Daniel-Jang** [comment]
I've just noticed the excel spreadsheet format after working on this ticket for a bit, will need to recode again to support that format but everything else works fine. Was about to submit a PR but will have to wait a bit unfortunately.

**Comment by j-selby** [comment]
@Daniel-Jang would it be easier to get them to export as a .csv from Excel? Especially if they shift their workflow to e.g. Google Docs or something in the future?

**Comment by Daniel-Jang** [comment]
> @Daniel-Jang would it be easier to get them to export as a .csv from Excel? Especially if they shift their workflow to e.g. Google Docs or something in the future?

Whoops, sorry I didn't see this earlier :/ 
Thankfully I got it working with excel though, and they would not need to do anything on their end in terms of formatting the file.
