### ISSUE TITLE
Search Tool/Auto-Complete Feature When Adding Courses to Subplans

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#219]
**(FEEDBACK FROM CASS' USER TESTING)**

Currently, a dropdown of courses who up when creating a Rule. This is insufficient as the usability of the UI will decrease as the number of courses grow in the database. Additionally, the order of courses in the dropdown menu changes.

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit

**Comment by joshcbee** [comment]
Implemented by #364
