### ISSUE TITLE
Add Option to Name/Label a List

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#220]
**(FEEDBACK FROM CASS' USER TESTING)**

The CASS clients would love a feature where they could name/label a list for future reference.

**NOTE:** POTENTIAL SCOPE CREEP

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit

**Comment by joshcbee** [comment]
#392 closes
