### ISSUE TITLE
Description Section Whilst Creating a List

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#221]
**(FEEDBACK FROM CASS' USER TESTING)**

The CASS clients requested a section where they could write a description for each List.

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit

**Comment by joshcbee** [comment]
#392 closes
