### ISSUE TITLE
Newly Created Subplan Not Being Displayed

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#222]
**(FEEDBACK FROM CASS' USER TESTING)**

Bug is yet to be reproduced by a developer.

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit

**Comment by JackSekoranja** [comment]
I believe this is happening as the newly created Subplan did not have the 'Publish' field marked. Maybe the way to fix this is to have the field marked by default

**Comment by JackSekoranja** [comment]
Closed as PR #351 should have fixed this issue since users are now notified if they try to save a non-published plan.
