### ISSUE TITLE
Problems With Display of Program

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#225]
**(FEEDBACK FROM CASS' USER TESTING)**

> "_Problems with display of Program – issue seems to be with EITHER / OR tool_" -Deborah Veness (CASS)

The actual issue is yet to be determined by the dev team. Please close this [git issue](https://github.com/cass-degrees/CASS-Degrees/issues/49) when the bug has been determined.

**Important Links:**
CASS’ UAT: https://docs.google.com/document/d/1YgSb5DiK-O8mrNe_oHAtijXuIVcSzRwb/edit

**Comment by joshcbee** [comment]
Unable to replicate a bug with this issue - likely an issue with publishing
