### ISSUE TITLE
Courses with dependencies prevents deletion of other marked courses

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#239]
During deletion, if even 1 course has a dependency issue, all the other courses that were marked for deletion won't be deleted.

![image](https://user-images.githubusercontent.com/37033052/63572549-75ad5100-c5c6-11e9-982f-eacb7d019f88.png)

All the courses that don't have dependency issues should be deleted.

**Comment by JackSekoranja** [comment]
Closed with PR #324
