### ISSUE TITLE
Input Subplan Identification Details (3)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#24]
As a CASS Staff member, 
I want to specify the year/type/title/code of the subplan,
So that I can uniquely identify the subplan and find it easily later.

**Acceptance Criteria:**
- While editing a subplan, the user can set the year the subplan is for, the title of the subplan, the code of the subplan, and whether it is a Major, Minor, or Specialisation
- If the year and title or year and code of the subplan match one already in the system, the user is notified that the current subplan is potentially a duplicate

**Comment by joshcbee** [comment]
Pull request submitted, modification of criteria 2 (year, title) restriction to a restriction on a duplicate (year, title, type).

**Comment by joshcbee** [comment]
Implemented and pulled to develop.

![image](https://user-images.githubusercontent.com/10462891/56345131-5c545c80-6202-11e9-9361-159bf52f58a3.png)
