### ISSUE TITLE
"General Elective" rule for subplans

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#268]
There is currently no option to add general electives when creating subplans, making requirements like "A minimum of 48 units from completion of elective courses offered by ANU" difficult. This can currently be achieved/bypassed by adding a "Custom (Text)" rule and clicking the "Show 6-unit course boxes in plans (e.g. PDF):" checkbox. However, IMO this is nowhere near obvious enough, especially given how common it is.

**Comment by aidengeorge97** [comment]
This issue already exists. See #265.
