### ISSUE TITLE
Checkboxes and other UI elements are too small

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#286]
Andrew noted that he found the UI to be very 'finnicky' and elements such as the checkboxes, dropdown menus to be a bit too small for his liking (he often misclicked on the elements).

He did note that he could fix it by zooming in.

Link: https://docs.google.com/document/d/1KfdzBN3GWYagc18__njZcWjA_km5c015UwtlQM5y_ww/edit#

**Comment by j-selby** [comment]
Implemented by #331, #336
