### ISSUE TITLE
Add Delete Feature in Edit Course/Subplan/Program

### ISSUE THREAD

**Issue by spencerj411** [j-selby/CASS-Degrees-Code#289]

**Comment by j-selby** [comment]
Is this so that they can delete the edited course/subplan/program, or something else?

**Comment by spencerj411** [comment]
Whilst they're editing a course/subplan/program have an option where you could delete that specific thing. Imo, this is useful for a case like this:
_User clicks on "Edit" on a certain course to look at course's info. User realises it is not needed. User wants to delete this specific course._

With this new feature, the user would not need to go back to the previous page, click the tickbox, scroll down and click the delete selected button.
