### ISSUE TITLE
Course Editing (5)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#31]
As a CASS Staff member,
I want to be able to edit courses that are offered in the college
So that I can correct any mistakes that were made when creating the course.

**Acceptance Criteria:**
- The user is able to select a course and modify the name, the requisites, the year it runs in, and the semesters it runs in
- The changes are updated in the system after saving

**Comment by Daniel-Jang** [comment]
Just a note, this is currently blocked until this pull request (https://github.com/cass-degrees/CASS-Degrees-Code/pull/58) is accepted and merged back into develop. I need to edit code in managecourses.html and manage_courses function in ui/views.py.

I will be helping out Spencer with that PR and then I will be able to work on this.
