### ISSUE TITLE
Implement Searchable Selection Fields for Adding Courses/Subplan Rules

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#318]
Josh has already created a type of searchable input field for adding courses to Lists. UAT revealed that this method of adding courses is greatly preferred to the existing drop down selection fields and is much faster. Existing drop down fields for adding lists of courses and subplans to rules should be replaced with this searchable input field.

**Comment by aidengeorge97** [comment]
Extends #219 but this issue references a broader range of fields.

**Comment by joshcbee** [comment]
#392 closed
