### ISSUE TITLE
Template/Subplan Removal (8)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#32]
As a CASS Staff member,
I want to be able to remove templates/subplans
So that I can ensure the templates/subplans on the system are accurate and up to date.

**Acceptance Criteria:**
- The user is able to select a template/subplan and remove it from the system
- The template/subplan no longer appears in the system after deletion
- In the case of a subplan deletion, the user will be notified if it is used in any templates, and will be asked to act on these before the deletion can occur

**Comment by KavsHub** [comment]
I've been working on this story for the past few days and I've looked into the PR and code for #61 and #29.
It's pretty much a repeat (i.e copy and replace of course deletion to work also for programs and subplans).
I think we should generalise the manage_courses function to handle the requests for all the sections.
I'm going to have a chat with Spencer and Daniel about this as for now I've made changes which will conflict with their code later.

**Comment by KavsHub** [comment]
Basic deletion has been completed in PR #70 - which has been merged.

To complete this story, we still need to complete the last acceptance criteria of:

- In the case of a subplan deletion, the user will be notified if it is used in any templates, and will be asked to act on these before the deletion can occur

**Comment by KavsHub** [comment]
PR's #70 and #97 (which have been merged successfully)
Complete this story.

Closing this issue now.
