### ISSUE TITLE
View Existing Plans/Subplans (8)

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#34]
As a CASS Staff member, 
I want to be able to view the details of an existing plan/subplan
So that I can be aware of the details of that plan.

**Acceptance Criteria:**
- Created templates can be displayed in a human-readable format, and correctly represent all information that was inputted into the template

**Comment by aidengeorge97** [comment]
Closed as of #94. View links now no longer direct to the api. Completion of this issue has spawned two maintenance issues #95 and #96, which focus on expanding view functionality as the project grows.
