### ISSUE TITLE
Make 'publish' option more obvious to the user

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#345]
During UAT, the 'publish' option didn't stand out much so it was missed often. I believe it is a combination of the fact that it is small and that it isn't very descriptive of what it does.

Kind of similar to #321. Perhaps provide a small description of what 'Publish' does and/or make the option stand out more compared to other options.

UAT Link: https://docs.google.com/document/d/1wk9sX77a6Vi7mha6BX23KsZodu_yuyDUunoW9eJvKIs/edit#

**Comment by KavsHub** [comment]
This has also been raised in #316 
Since this is an ongoing issue we should prioritise this.

**Comment by JackSekoranja** [comment]
Closed with PR #388
