### ISSUE TITLE
Add `Custom (Text)`  and `either_or` rules in subplan creation

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#357]
Some subplans have rules that we can't currently express with the current subplan creation system. Consider the Advanced Studies Minor (https://programsandcourses.anu.edu.au/2019/minor/ADST-MIN), especally the rule that is as follows:

> And either:
>>Completion of the equivalent of 12 units in NUS modular credits of Independent Study Modules (ISMs) at National University of Singapore

>Or:
>>12 units from completion of the following course(s):
>>...

**Comment by spencerj411** [comment]
is closed by #424
