### ISSUE TITLE
Checkmarks are visible/interactive through popups

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#358]
When viewing a page with a popup open, if a checkmark appears beneath it then it is both visible and blocks the input of other elements on the popup.

**Checkmark visible through text box:**
![Screen Shot 2019-09-16 at 5 49 31 pm](https://user-images.githubusercontent.com/36946090/64942407-4da2cc00-d8ac-11e9-9ed0-b7850b2d8f0f.jpg)

**Checkmark visible through faded background:**
![Screen Shot 2019-09-16 at 5 52 52 pm](https://user-images.githubusercontent.com/36946090/64942408-4da2cc00-d8ac-11e9-88cc-4b483bfcf9c0.jpg)

**Comment by spencerj411** [comment]
See #344 for another example

**Comment by JackSekoranja** [comment]
Closed due to duplicate issue
