### ISSUE TITLE
Replace "No More than" and "No Less than" with "Minimum" and "Maximum"

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#359]
When creating subplans and programs, course lists on P&C don't specify an exact number are written "A *Minimum* of" and "A *Maximum* of", whereas we specify it as "No more than" and "At least". 

After making a few subplans it becomes very annoying to have to translate between the two, so this issue is about making the terminology consistent between our app and P&C.

**Comment by spencerj411** [comment]
#403 closes this issue.
