### ISSUE TITLE
List feature currently broken

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#365]
There currently seems to be a lot of issues surrounding the recently added "Lists" feature. Clicking "View" on the lists section doesn't work, so we will need to define a "view" option for lists. Also if a new list has the same name and year as an existing one it will crash.

**Comment by joshcbee** [comment]
Can you check if this is still happening with in the PR branch, there was a lot of updating needed due to changes in develop. If so, could you provide a screenshot?

**Comment by joshcbee** [comment]
resolved by #381
