### ISSUE TITLE
Error When Bulk Uploading Invalid File Types

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#370]
The bulk upload feature should perform a check to ensure that the chosen file type is valid and return a corresponding error message.

When uploading an mp4 file:

![image](https://user-images.githubusercontent.com/37424867/65119119-3809df80-da2f-11e9-8cea-ca68ace3587c.png)

**Comment by KavsHub** [comment]
Closed by PR #375
