### ISSUE TITLE
Notify the user if they create a subplan/program with no rules

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#372]
In recent UAT the tester created a subplan for use in the program plan, but did not specify any rules. To fix this we could add a popup similar to the one that was implemented in PR #351 that will activate when the user adds a plan with no units. 

This could be extended later in the project to pop up once all units have been completed, as that might be something we'd want to do in the future.

UAT Document: https://docs.google.com/document/d/17vDpVLtRfp05KepaEAJbG118ecldQtxiap_FCheVNnw/edit#

**Comment by KavsHub** [comment]
#388, may as well look into standardising popups/notifications while I'm doing the tooltips

**Comment by JackSekoranja** [comment]
Closed with PR #382
