### ISSUE TITLE
Make new lists update the rule error messages

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#373]
Recent UAT revealed that the new course lists don't update the rest of the component. This means error messages remain when they should disappear. For example: 
1. Add a new `Course` rule
2. Populate the `At Least`/`Exactly`/`No More Than` and `Units` options. You should see an error like "*You need to fill in all fields*"
3. Add a course using the menu. The error message will still persist even though it should disappear

This issue is probably occuring as the new list is not calling the `check_options` rule, so if that is added using `v-on:change` it should work normally

UAT Document: https://docs.google.com/document/d/17vDpVLtRfp05KepaEAJbG118ecldQtxiap_FCheVNnw/edit#

**Comment by joshcbee** [comment]
@JackSekoranja check fixed?

**Comment by joshcbee** [comment]
Appears to have been resolved by a previous PR for Programs and Subplans. On trying to replicate, the error message now only shows when a user attempts to save, and resolves when they add a course. In Create List, the courses must be added message persists, will put through a fix now.

**Comment by joshcbee** [comment]
On further investigation, the error message in the Create Lists page is different to the messages in course rules as it is Django form based not vue.js based. The default behaviour for all django error fields (see program details year, name, etc. for example) is that the error is rechecked on submission, and with messages re-rendered accordingly. No further action.
