### ISSUE TITLE
Attempting to create an empty list results in unintuitive error

### ISSUE THREAD

**Issue by j-selby** [j-selby/CASS-Degrees-Code#393]
When attempting to create a course list, filling in fields but not adding any courses, an error is shown when attempting to save this list which doesn't demonstrate well that the issue with this is related to the lack of courses, rather than the year or otherwise. This would likely require some kind of manual verification before checking.

![image](https://user-images.githubusercontent.com/1404334/65477039-8296bc00-de74-11e9-9dda-34436cc9c4eb.png)

**Comment by joshcbee** [comment]
Raised in UAT 25/9
