### ISSUE TITLE
Rules can't distinguish between different courses with the same course code

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#397]
Since rules only stores course codes, there is no way to distinguish between courses with same code but with different names. 

Example: 
How it was saved:
![image](https://user-images.githubusercontent.com/37033052/65500510-c2a48000-df02-11e9-8d7c-d04542a38874.png)

What it loads as when you click to edit again:
![image](https://user-images.githubusercontent.com/37033052/65500750-1fa03600-df03-11e9-8c0d-5b47a2828bbe.png)

**Comment by joshcbee** [comment]
Perhaps this is one we can solve through a business rule rather than a coding change, i.e. if both the in person and online delivery fulfils the requirement to complete ARAB6501, should they even be separate courses in the list?

**Comment by joshcbee** [comment]
#414 will address this issue following discussion with clients wk 8 - course codes to be unique.
