### ISSUE TITLE
Implement a PEP 8 Checker

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#40]
Implement some kind of a pep 8 ([Python code style guide](https://www.python.org/dev/peps/pep-0008/)) checker that checks the entire code base and reports any pep 8 violations.

Acceptance Criteria:
- Implement a pep 8 checker (as per description).
- Customisable. Allows exceptions and modifications to the default rules in the pep 8 checker of choice.

**Comment by j-selby** [comment]
Implemented in #54
