### ISSUE TITLE
Rule creation gets locked in error state if there are no courses in the system

### ISSUE THREAD

**Issue by joshcbee** [j-selby/CASS-Degrees-Code#409]
Also relates to #395 ?

Once the error for rule creation is triggered, it does not refresh e.g. when a user has gone to create subplans or courses and should now be able to create the plan.

![image](https://user-images.githubusercontent.com/10462891/65593345-a1f82b00-dfd3-11e9-8694-20ceaddef564.png)

**Comment by JackSekoranja** [comment]
Already fixed from previous PRs
