### ISSUE TITLE
Create Empty Data Tables

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#41]
This task will be to implement the schema of the database so that we can start filling them in.

**Comment by aidengeorge97** [comment]
Created tables for storing static Course, Degree, and Subplan information. Data can now be stored in these tables, and courses can be linked to subplans. 

Not included:
- Tight restrictions on variable values. 
- Functionality to store degree rules
- Functionality to store requisites and incompatibilities fro courses
