### ISSUE TITLE
Student-facing plan creation broken

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#416]
Currently the student-facing side cannot load any new or old plans, showing a `string indices must be integers` error. This basically breaks the entire student-facing system.

**Comment by j-selby** [comment]
Is this still an issue? I was able to save/load a plan fine for this one.

**Comment by JackSekoranja** [comment]
Resolved from recent PRs

**Comment by JackSekoranja** [comment]
Reopened as the issue has re-appeared
