### ISSUE TITLE
Create Sample Data

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#42]
NOTE: Also requires definition of the Template Structure. This shouldn't be done independently, so consult other team members or facilitate a discussion with all group members.

This task requires the addition of at least one template, one subplan, and one or more courses. This data should be valid data (i.e. from P&C), and requires the completion of Issue #41 beforehand.

**Comment by aidengeorge97** [comment]
Reevaluated as non-essential for MVP and doesn't bring value to clients. Developers can create their own testing data as required.
