### ISSUE TITLE
Setup Main Menu Styling/Navagation

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#44]
Setup a main menu in Django allowing navigation to all of the required/reasonable page elements (i.e, Template creation, subplan creation, etc.). Ensure this is designed to be modular (So we can add any necessary elements) and that others can easily go in and link to the correct pages

**Comment by joshcbee** [comment]
Main menu implemented. Assets to be refined at later stage.

![Cropped main menu](https://user-images.githubusercontent.com/10462891/55938893-c3f92d80-5c7f-11e9-8ecf-b1617a55881b.jpg)
