### ISSUE TITLE
Database-Security

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#5]
Currently, anyone can access the API created from issue https://github.com/cass-degrees/CASS-Degrees-Code/issues/3. This should be remedied somewhat with some security controls and authentication. Only the Django app and other authorised users (e.g. clients or our project managers) should be able to add, modify and edit course details stored in db, for example.

There are some details regarding authentication on this website: 
https://wsvincent.com/official-django-rest-framework-tutorial-beginners-guide/

Look into this import for authentication:
from django.contrib.auth.models import User

**Comment by JackSekoranja** [comment]
Closed with PR #155
