### ISSUE TITLE
Add Course Rules

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#78]
As a CASS Staff Member,
I want to be able to define the course rules with requisites and incompatible courses when creating a new course, so that I can save and record the requisites and incompatible courses for every course.

**Acceptance Criteria:**
- User can define requisites like such: "Must have done X or Y" or "Must have done A and B"
- User can define incompatible courses like such: "Incompatible with M and N"

**Comment by spencerj411** [comment]
done - see #156.
