### ISSUE TITLE
Modify requisites in course creation/editing to support complex requisites

### ISSUE THREAD

**Issue by JackSekoranja** [j-selby/CASS-Degrees-Code#81]
Currently course requisites and incompatibilities are created by selecting multiple courses from a list. However, not all requisites/incompatibilities are representable in this format, as some have logic such as "Completion of (A and (B or C))", and can even have additional criteria such as "Must get a permission code" or "Must be studying X". 

There are several approaches we could take to solve these issues:
1. Use program/subplan rules logic to represent this information (More complex than needed)
2. Have a simple course list that indicates a relationship with the course, and have a text section below describing the rules (Easy to do/understand but will lose some representation)
3. Use basic AND/OR logic to represent requisites, and an optional text input for other options
4. Mixture of above suggestions

Might want to discuss the best option to take with team (I personally think 3 is a good idea)

Outlier Course examples:
- Permission code & unit requirement: https://programsandcourses.anu.edu.au/2019/course/ASIA2107
- Must be studying X: https://programsandcourses.anu.edu.au/2019/course/BUSN7051
- Mixed rules: https://programsandcourses.anu.edu.au/2019/course/LAWS2201

**Comment by Daniel-Jang** [comment]
Different Types of Requisites/Incompatibilities **(NOTE: requisites will be in an AND/OR logic format)**:
- "Inherent Requirements"??? - could be ignored, search for definition.
- X units of university courses: 
Eg. _24 units of university courses_
- X units of subject-specific courses: 
Eg. _12 units of COMP courses_
- X units of year-specific courses: 
Eg. _48 units of 2000-level courses_
- X units of subject and year specific courses: 
Eg. _12 units of COMP3000 courses_
- Specific courses: 
Eg. _must have completed LAWS1000_
- Concurrent enrolment: 
Eg. _You currently must be completing five 1000-level LAWS courses, You currently must be studying X_
- Must currently be studying a certain program:
Eg. _You must be studying a program which includes Bachelor of Laws_
- Must ask for a permission code
- Incompatible with X **(will only be represented using AND):**
Eg. _This course is incompatible with BUSN3051_

**Comment by spencerj411** [comment]
done - see #156.
