### ISSUE TITLE
Program Code Length Restriction Too Long

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#88]
Currently program codes are restricted to be greater than 3 characters in length, however there exist programs with only 2 characters (See Bachelor of Arts - BA).

**Comment by joshcbee** [comment]
Is this a historic code? The current formal code for Bachelor of Arts is BARTS
https://programsandcourses.anu.edu.au/program/BARTS

**Comment by aidengeorge97** [comment]
Tight yea cool, I misread the program page. I was also thinking of the BIT but that would be covered by a minimum 3 anyway. All is fine.
