### ISSUE TITLE
Update Program/Subplan View Pages With New Rules

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#95]
As new program and subplan rules are added to the system, the view pages will need to be updated to neatly display these.

**Comment by aidengeorge97** [comment]
See the [rules and requirements document](https://docs.google.com/document/d/13rDT9u6-vEgFtUdmtDeBNE_8HUAiiQryGiRG5CbEsxA/edit) for a comprehensive list on the rules the view page must be able to display.

**Comment by j-selby** [comment]
Program PDF still needs either/or implemented.

Everything else is up to date, and this can be closed afterwards (noting that PRs adding rules should also add implementations for this in the future).
