### ISSUE TITLE
Update Course View Pages With Requisites and Incompatibilities

### ISSUE THREAD

**Issue by aidengeorge97** [j-selby/CASS-Degrees-Code#96]
The course view page will need to be updated as functionality for requisites and incompatibilities is added to the system.

**Comment by aidengeorge97** [comment]
See the [rules and requirements document](https://docs.google.com/document/d/13rDT9u6-vEgFtUdmtDeBNE_8HUAiiQryGiRG5CbEsxA/edit) for a comprehensive list on the rules the view page must be able to display.

**Comment by j-selby** [comment]
Implemented by 25a6bf64e4b48bf5e15ef9fbe00e6e9b941779bd
